import { Book, Scholarship, VolunteerSession } from './types';

export const mockBooks: Book[] = [
  { id: '1', title: 'تعلیمات اسلامی', grade: 'صنف ۱۲', subject: 'اسلامیات', category: 'لیسه' },
  { id: '2', title: 'جعفری', grade: 'صنف ۱۲', subject: 'اسلامیات', category: 'لیسه' },
  { id: '3', title: 'ریاضی', grade: 'صنف ۱۲', subject: 'ریاضی', category: 'لیسه' },
  { id: '4', title: 'كمپيوتر', grade: 'صنف ۱۲', subject: 'ساینس', category: 'لیسه' },
  { id: '5', title: 'بیالوژی', grade: 'صنف ۱۲', subject: 'ساینس', category: 'لیسه' },
  { id: '6', title: 'پشتو', grade: 'صنف ۱۲', subject: 'زبان', category: 'لیسه' },
  { id: '7', title: 'جغرافیه', grade: 'صنف ۱۲', subject: 'اجتماعیات', category: 'لیسه' },
  { id: '8', title: 'تاریخ', grade: 'صنف ۱۲', subject: 'اجتماعیات', category: 'لیسه' },
  { id: '9', title: 'فزیک', grade: 'صنف ۱۲', subject: 'ساینس', category: 'لیسه' },
  { id: '10', title: 'کیمیا', grade: 'صنف ۱۲', subject: 'ساینس', category: 'لیسه' },
  { id: '11', title: 'م.مدنی', grade: 'صنف ۱۲', subject: 'اجتماعیات', category: 'لیسه' },
  { id: '12', title: 'انګلیسي', grade: 'صنف ۱۲', subject: 'زبان', category: 'لیسه' },
  { id: '13', title: 'دری', grade: 'صنف ۱۲', subject: 'زبان', category: 'لیسه' },
  { id: '14', title: 'تفسیر شریف', grade: 'صنف ۱۲', subject: 'اسلامیات', category: 'لیسه' },
  { id: '15', title: 'فزیک', grade: 'صنف ۱۱', subject: 'ساینس', category: 'لیسه' },
  { id: '16', title: 'کیمیا', grade: 'صنف ۱۰', subject: 'ساینس', category: 'لیسه' },
  { id: '17', title: 'تاریخ', grade: 'صنف ۹', subject: 'اجتماعیات', category: 'متوسطه' },
];

export const mockScholarships: Scholarship[] = [
  {
    id: 's1',
    name: 'UWC High School Scholarship 2026 Entry',
    gender: 'همه',
    country: 'آلمان',
    levels: ['مکتب'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Boys & Girls (Ages 15-18)',
    description: 'Fully Funded On-Campus (International)',
    link: 'https://apply.uwc.org/'
  },
  {
    id: 's2',
    name: 'Global Korea Scholarship (GKS)',
    gender: 'همه',
    country: 'کره جنوبی',
    levels: ['لیسانس', 'ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Afghan Students',
    description: 'Fully Funded (Tuition, Stipend, Flights, Language Year) in South Korea.',
    link: 'https://www.studyinkorea.go.kr/'
  },
  {
    id: 's3',
    name: 'Japanese Government (MEXT) Scholarship',
    gender: 'همه',
    country: 'جاپان',
    levels: ['لیسانس', 'ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'Fully Funded On-Campus (Japan).',
    link: 'https://www.afg.emb-japan.go.jp/'
  },
  {
    id: 's4',
    name: 'Türkiye Bursları Government Scholarships',
    gender: 'همه',
    country: 'ترکیه',
    levels: ['لیسانس', 'ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International',
    description: 'Fully Funded (Tuition, Dormitory, Health Insurance, Monthly Stipend) in Turkey.',
    link: 'https://www.turkiyeburslari.gov.tr/'
  },
  {
    id: 's5',
    name: 'SBW Berlin Scholarship',
    gender: 'همه',
    country: 'آلمان',
    levels: ['لیسانس', 'ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Refugees & International Students (Ages 18-30)',
    description: 'Fully Funded (Tuition, Free Shared Flat Accommodation, Monthly Stipend) in Germany.',
    link: 'https://sbw.berlin/en/'
  },
  {
    id: 's6',
    name: 'UK Chevening Master\'s Scholarship',
    gender: 'همه',
    country: 'انگلستان',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'All Graduates (Minimum 2 years work/volunteer experience)',
    description: 'Fully Funded On-Campus (United Kingdom).',
    link: 'https://www.chevening.org/'
  },
  {
    id: 's7',
    name: 'Bard College Berlin PIESC Scholarship',
    gender: 'همه',
    country: 'آلمان',
    levels: ['لیسانس'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Students from Conflict-Affected Areas',
    description: 'Fully Funded On-Campus (Germany).',
    link: 'https://berlin.bard.edu/'
  },
  {
    id: 's8',
    name: 'University of the People Online Degree',
    gender: 'همه',
    country: 'ایالات متحده (آنلاین)',
    levels: ['لیسانس', 'ماستری'],
    format: 'آنلاین',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'All Afghan Students (Girls & Boys)',
    description: 'Tuition-Free (Computer Science, Business, Health Science) 100% Online.',
    link: 'https://www.uopeople.edu/'
  },
  {
    id: 's9',
    name: 'Helmut Veith Stipend for Women in Computer Science',
    gender: 'دخترانه',
    country: 'اتریش',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Female Students Only',
    description: 'Fully Funded (EUR 7,000/year + Tuition Waiver) On-Campus (Austria / TU Wien).',
    link: 'https://www.tuwien.at/'
  },
  {
    id: 's10',
    name: 'Stipendium Hungaricum Hungarian Government Scholarship',
    gender: 'همه',
    country: 'مجارستان',
    levels: ['لیسانس', 'ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'Fully Funded (Tuition, Monthly Allowance, Housing Contribution) On-Campus (Hungary / Europe).',
    link: 'https://stipendiumhungaricum.hu/'
  },
  {
    id: 's11',
    name: 'Islamic Development Bank (IsDB) Scholarship',
    gender: 'همه',
    country: 'کشورهای عضو',
    levels: ['لیسانس', 'ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students from member countries',
    description: 'Fully Funded On-Campus (Global Member Institutions).',
    link: 'https://www.isdb.org/scholarships'
  },
  {
    id: 's12',
    name: 'Erasmus Mundus Joint Master Degrees (EMJMD)',
    gender: 'همه',
    country: 'اروپا',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'All Graduates',
    description: 'Fully Funded (Travel, Visa, Monthly Allowance) On-Campus (Multiple European Universities).',
    link: 'https://erasmus-plus.ec.europa.eu/'
  },
  {
    id: 's13',
    name: 'AAUW International Fellowships for Women',
    gender: 'دخترانه',
    country: 'ایالات متحده',
    levels: ['ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Female Students Only',
    description: 'Fully Funded ($20,000–$50,000 stipend) On-Campus (USA).',
    link: 'https://www.aauw.org/'
  },
  {
    id: 's14',
    name: 'ICCR Scholarships (Online & Distance)',
    gender: 'همه',
    country: 'هند (آنلاین)',
    levels: ['لیسانس', 'ماستری'],
    format: 'آنلاین',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'Fully Funded E-Learning Degrees.',
    link: 'https://www.iccr.gov.in/'
  },
  {
    id: 's15',
    name: 'Right To Learn (CW4WAfghan) Secondary Courses',
    gender: 'دخترانه',
    country: 'کانادا (آنلاین)',
    levels: ['مکتب'],
    format: 'آنلاین',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Afghan Girls & Women',
    description: '100% Free 100% Online Secondary Courses.',
    link: 'https://www.cw4wafghan.ca/'
  },
  {
    id: 's16',
    name: 'Flex / YES High School Exchange Program',
    gender: 'همه',
    country: 'ایالات متحده',
    levels: ['مکتب'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Boys & Girls (Ages 15-17)',
    description: 'Fully Funded (1 Academic Year in US High School).',
    link: 'https://www.yesprograms.org/'
  },
  {
    id: 's17',
    name: 'Fulbright Foreign Student Program',
    gender: 'همه',
    country: 'ایالات متحده',
    levels: ['ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'Fully funded scholarship for international students pursuing Master’s or PhD.',
    link: 'https://foreign.fulbrightonline.org/'
  },
  {
    id: 's18',
    name: 'DAAD Scholarships',
    gender: 'همه',
    country: 'آلمان',
    levels: ['ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Graduates and Doctoral Students',
    description: 'Offers fully funded scholarships for a range of postgraduate courses in German Universities.',
    link: 'https://www.daad.de/'
  },
  {
    id: 's19',
    name: 'Eiffel Excellence Scholarship Programme',
    gender: 'همه',
    country: 'فرانسه',
    levels: ['ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'Funded by the French Ministry for Europe and Foreign Affairs.',
    link: 'https://www.campusfrance.org/'
  },
  {
    id: 's20',
    name: 'Swedish Institute Scholarships for Global Professionals',
    gender: 'همه',
    country: 'سوئد',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Highly qualified international students',
    description: 'Fully funded scholarship for master’s degree studies in Sweden.',
    link: 'https://si.se/'
  },
  {
    id: 's21',
    name: 'Australia Awards Scholarships',
    gender: 'همه',
    country: 'استرالیا',
    levels: ['لیسانس', 'ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Students from developing countries',
    description: 'Provides full tuition fees, return air travel, establishment allowance, and living expenses.',
    link: 'https://www.dfat.gov.au/'
  },
  {
    id: 's22',
    name: 'Gates Cambridge Scholarships',
    gender: 'همه',
    country: 'انگلستان',
    levels: ['ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Outstanding applicants from outside the UK',
    description: 'Fully funded postgraduate degree in any subject available at the University of Cambridge.',
    link: 'https://www.gatescambridge.org/'
  },
  {
    id: 's23',
    name: 'Rhodes Scholarship',
    gender: 'همه',
    country: 'انگلستان',
    levels: ['ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'The oldest international fellowship program in the world at the University of Oxford.',
    link: 'https://www.rhodeshouse.ox.ac.uk/'
  },
  {
    id: 's24',
    name: 'Swiss Government Excellence Scholarships',
    gender: 'همه',
    country: 'سوئیس',
    levels: ['دکترا', 'ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'Aimed at young researchers from abroad who have completed a master’s degree or PhD.',
    link: 'https://www.sbfi.admin.ch/'
  },
  {
    id: 's25',
    name: 'Vanier Canada Graduate Scholarships',
    gender: 'همه',
    country: 'کانادا',
    levels: ['دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International doctoral students',
    description: '$50,000 per year for three years during doctoral studies.',
    link: 'https://vanier.gc.ca/'
  },
  {
    id: 's26',
    name: 'Lester B. Pearson International Scholarships',
    gender: 'همه',
    country: 'کانادا',
    levels: ['لیسانس'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International students nominated by their school',
    description: 'Provides fully funded bachelor degrees at the University of Toronto.',
    link: 'https://future.utoronto.ca/'
  },
  {
    id: 's27',
    name: 'ADB-Japan Scholarship Program',
    gender: 'همه',
    country: 'جاپان',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Citizens of ADB borrowing member countries',
    description: 'Full tuition, monthly allowance, housing, books, and medical insurance.',
    link: 'https://www.adb.org/'
  },
  {
    id: 's28',
    name: 'KOICA Scholarship Program',
    gender: 'همه',
    country: 'کره جنوبی',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Government officials and public sector employees',
    description: 'Fully funded master’s degree programs at participating Korean universities.',
    link: 'https://www.koica.go.kr/'
  },
  {
    id: 's29',
    name: 'CSC Scholarships',
    gender: 'همه',
    country: 'چین',
    levels: ['لیسانس', 'ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'Chinese Government Scholarships covering tuition, accommodation, and stipend.',
    link: 'https://www.campuschina.org/'
  },
  {
    id: 's30',
    name: 'Schwarzman Scholars',
    gender: 'همه',
    country: 'چین',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'Fully funded master’s degree in Global Affairs at Tsinghua University.',
    link: 'https://www.schwarzmanscholars.org/'
  },
  {
    id: 's31',
    name: 'Thai Government Scholarships (TICA)',
    gender: 'همه',
    country: 'تایلند',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'Fully funded master’s degree for developing countries.',
    link: 'https://tica-thaigov.mfa.go.th/'
  },
  {
    id: 's32',
    name: 'Singapore International Graduate Award (SINGA)',
    gender: 'همه',
    country: 'سنگاپور',
    levels: ['دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students in Science and Engineering',
    description: 'Fully funded PhD in Singapore.',
    link: 'https://www.a-star.edu.sg/singa'
  },
  {
    id: 's33',
    name: 'New Zealand International Scholarships',
    gender: 'همه',
    country: 'نیوزیلند',
    levels: ['لیسانس', 'ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Students from eligible countries',
    description: 'Fully funded tuition, travel, and living costs in New Zealand.',
    link: 'https://www.nzscholarships.govt.nz/'
  },
  {
    id: 's34',
    name: 'VLIR-UOS Awards Scholarships',
    gender: 'همه',
    country: 'بلژیک',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Students from developing countries',
    description: 'Covers tuition, travel, insurance, and living expenses.',
    link: 'https://www.vliruos.be/'
  },
  {
    id: 's35',
    name: 'Orange Knowledge Programme',
    gender: 'همه',
    country: 'هلند',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Professionals from developing countries',
    description: 'Fully funded scholarships to study in the Netherlands.',
    link: 'https://www.studyinnl.org/'
  },
  {
    id: 's36',
    name: 'ETH Zurich Excellence Master\'s Scholarships',
    gender: 'همه',
    country: 'سوئیس',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Outstanding international students',
    description: 'Grant covering living and study expenses for a Master’s degree at ETH Zurich.',
    link: 'https://ethz.ch/'
  },
  {
    id: 's37',
    name: 'Knight-Hennessy Scholars',
    gender: 'همه',
    country: 'ایالات متحده',
    levels: ['ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'Fully funded graduate studies at Stanford University.',
    link: 'https://knight-hennessy.stanford.edu/'
  },
  {
    id: 's38',
    name: 'Joint Japan World Bank Graduate Scholarship',
    gender: 'همه',
    country: 'کشورهای مختلف',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Developing country nationals',
    description: 'Fully funded master’s degree in development-related fields.',
    link: 'https://www.worldbank.org/'
  },
  {
    id: 's39',
    name: 'Aga Khan Foundation International Scholarship',
    gender: 'همه',
    country: 'جهانی',
    levels: ['ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'بورسیه درصدی',
    isVerified: true,
    targetAudience: 'Outstanding students from developing countries',
    description: '50% grant and 50% loan for postgraduate studies.',
    link: 'https://the.akdn/'
  },
  {
    id: 's40',
    name: 'Qalaa Holdings Scholarship',
    gender: 'همه',
    country: 'مصر',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Arab and African nationals',
    description: 'Fully funded postgraduate studies for students in the region.',
    link: 'http://qalaascholarships.org/'
  },
  {
    id: 's41',
    name: 'Al Qasimi Foundation Grants',
    gender: 'همه',
    country: 'امارات متحده عربی',
    levels: ['دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International doctoral researchers',
    description: 'Fully funded field research in the UAE.',
    link: 'https://www.alqasimifoundation.com/'
  },
  {
    id: 's42',
    name: 'Doha Institute for Graduate Studies',
    gender: 'همه',
    country: 'قطر',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'Fully funded master’s degrees covering tuition, accommodation, and stipend.',
    link: 'https://www.dohainstitute.edu.qa/'
  },
  {
    id: 's43',
    name: 'KAUST Fellowship',
    gender: 'همه',
    country: 'عربستان سعودی',
    levels: ['ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Science and Engineering Students',
    description: 'Fully funded graduate programs including tuition, housing, and stipend.',
    link: 'https://www.kaust.edu.sa/'
  },
  {
    id: 's44',
    name: 'Invest Your Talent in Italy',
    gender: 'همه',
    country: 'ایتالیا',
    levels: ['ماستری'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'Students from selected countries',
    description: 'Fully funded master’s programs in Italy with a professional internship.',
    link: 'https://investyourtalentapplication.esteri.it/'
  },
  {
    id: 's45',
    name: 'Romanian Government Scholarships',
    gender: 'همه',
    country: 'رومانیا',
    levels: ['لیسانس', 'ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students (non-EU)',
    description: 'Fully funded studies in Romania for undergraduate and postgraduate levels.',
    link: 'https://www.mae.ro/'
  },
  {
    id: 's46',
    name: 'Mexican Government Scholarships',
    gender: 'همه',
    country: 'مکزیک',
    levels: ['لیسانس', 'ماستری', 'دکترا'],
    format: 'حضوری',
    coverage: 'کاملاً رایگان',
    isVerified: true,
    targetAudience: 'International Students',
    description: 'Fully funded studies in Mexico for international students.',
    link: 'https://www.gob.mx/amexcid'
  }
];


export const mockVolunteers: VolunteerSession[] = [
  {
    id: 'v1',
    subject: 'آمادگی تافل (TOEFL Prep)',
    tutor: 'استاد احمدی',
    platform: 'Google Meet',
    schedule: 'روزهای طاق، ساعت ۴ بعد از ظهر'
  },
  {
    id: 'v2',
    subject: 'برنامه‌نویسی وب (پایتون/ری‌اکت)',
    tutor: 'انجنیر نوری',
    platform: 'Telegram Group',
    schedule: 'پنج‌شنبه‌ها، ساعت ۸ شب'
  },
  {
    id: 'v3',
    subject: 'ریاضیات عالی (آمادگی کانکور)',
    tutor: 'استاد رحیمی',
    platform: 'Zoom',
    schedule: 'روزهای جفت، ساعت ۵ عصر'
  }
];
