-- ==========================================
-- Supabase SQL Schema for Volunteer Registration
-- ==========================================

-- 1. Create the 'volunteers' table
CREATE TABLE public.volunteers (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    full_name text not null,
    contact_info text not null,
    subject_expertise text not null,
    motivation text not null,
    status text default 'pending'::text not null
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.volunteers ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policy allowing ANONYMOUS users to INSERT new applications
CREATE POLICY "Allow anonymous users to insert volunteers" 
ON public.volunteers
FOR INSERT 
TO anon 
WITH CHECK (true);

-- 4. Create RLS Policy preventing public users from SELECTING or reading entries
-- We create a policy that returns 'false' for SELECT for the 'anon' role.
-- (By default, if no SELECT policy exists for a role, they can't read anyway, 
-- but explicitly denying it is a good practice or just rely on default-deny).
CREATE POLICY "Deny anonymous read access to volunteers"
ON public.volunteers
FOR SELECT
TO anon
USING (false);

-- (Optional) If you have an authenticated admin role, you can add:
-- CREATE POLICY "Allow authenticated users to read volunteers" 
-- ON public.volunteers FOR SELECT TO authenticated USING (true);
