-- ==========================================
-- Supabase SQL Schema for Students and Volunteers
-- ==========================================

-- 1. Create the 'volunteers' table
CREATE TABLE IF NOT EXISTS public.volunteers (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    full_name text not null,
    contact_info text not null,
    subject_expertise text not null,
    motivation text not null,
    status text default 'pending'::text not null
);

-- 2. Create the 'students' table
CREATE TABLE IF NOT EXISTS public.students (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    full_name text not null,
    email text not null,
    grade_level text not null,
    status text default 'active'::text not null
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.volunteers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for 'volunteers'
CREATE POLICY "Allow anonymous users to insert volunteers" 
ON public.volunteers FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Deny anonymous read access to volunteers"
ON public.volunteers FOR SELECT TO anon USING (false);

-- 5. Create RLS Policies for 'students'
CREATE POLICY "Allow anonymous users to insert students" 
ON public.students FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "Deny anonymous read access to students"
ON public.students FOR SELECT TO anon USING (false);

